---
- name: Start Docker containers
  hosts: localhost

  tasks:
    - name: Ensure docker service is running
      systemd:
        name: docker
        state: started
        enabled: yes
      become: true
